---
type: jbackup.conf.v1
title: Test Basic Backup
look_for_dests:
    - type: mount
      mount: /media/jleblanc/think-backup
      path: test1
sources:
    - name: Main directories
      dest: ''
      sources:
        - sandbox/jtest

    - name: Dot Files
      dest: dot-files
      sources:
        - .bashrc
        - .bashrc.d
        - .tmux.conf
        - .tmux.conf.d

