# Test Toml file

type = "jbackup.conf.v1"
title = "Thinkpad Basic Backup"

[[look_for_dests]]
type = "mount"
mount = "/media/jleblanc/tpad"
path = "home"

[[sources]]
name = "Main Directories"
dest = ""
sources__ARR = """
admin
archive
code
# library
# mock-server
sandbox
"""

[[sources]]
name = "Default Directories"
dest = ""
sources__ARR = """
Desktop
Documents
Downloads
Yaks
Pictures
"""

[[sources]]
name = "Dot Files"
dest = "dot-files"
sources__ARR = """
.bash_aliases
# .bash_history
# .bash_logout
.bashrc
# .bashrc~
.bashrc.d
# .cache
# .config
# .cups
.emacs.d
.gitconfig
# .gnome
.gnupg
# .gphoto
# .lesshst
# .local
# .mozilla
.password-store
.pki
.profile
# .python_history
# .sane
.sqlite_history
.ssh
# .sudo_as_admin_successful
.tmux.conf
.tmux.conf.d
"""



